### ISSUE TITLE
WG recordings

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-wg#519] opened 2020-10-02 14:27 UTC
We have zoom recordings of previous calls that include automatic transcription.
Please don't reference these recordings because we have storage limits on our Zoom plan so these links can become inactive at some point.
Youtube videos for linking purposes: https://www.youtube.com/channel/UCERcwLeheOXp_u61jEXxHMA
**Password for Zoom recordings is `graphqlwg`**

## GraphQL WG

* Nov 7, 2019 [Zoom](https://zoom.us/rec/share/MvKlLk08uCkRwlgjka-prrbN4gqcwlHQgEjjoZ2SGxzQs9AQbelaViALqD5t-yzU.qu95hv1IJc0ZEIbe?startTime=1573146152000) [Youtube](https://www.youtube.com/watch?v=fbcTVULqm-8)
* Dec 5, 2019 [Zoom](https://zoom.us/rec/share/lPjJyYL4NGzYxQIMKAFenWlaOqkFW54_XXPOuxATNmJxZG8qW7d0s73iDGo-azqO.Z9iOqxVYumouyGlT?startTime=1575565536000) [Youtube](https://www.youtube.com/watch?v=XzEHLpMq13A)
* Feb 6, 2020 [Zoom](https://zoom.us/rec/share/vmjSOKT-_rjole_uDe_9eRwbk-NiILIxr7iPUhoSgrnQ_9G3rGzLxQ6fANNqdQQA.JAuCyvWcSYhulekX?startTime=1581009085000) [Youtube](https://www.youtube.com/watch?v=a0xwVVhH6rI)
* Mar 5, 2020 [Zoom](https://zoom.us/rec/share/JEovs7Rcmtl0CyoCN26lC1dfS7s2XE_Neyb2oHBTVWxpy9N4F-hXC5qEzkiIGFTf.BavBdeBsNGjkPj9m?startTime=1583428327000) [Youtube](https://www.youtube.com/watch?v=aezw-RYYDwY)
* Apr 2, 2020 [Zoom](https://zoom.us/rec/share/RIZBf-ttVsVOdQ120OgLWJYqwWkl27l36mrE0rWkftRn2U4IHT3CDlcqezzNtI2y.eiHJt4IOmvty6t9z?startTime=1585843194000) [Youtube](https://www.youtube.com/watch?v=bCXQsfIgTng)
* May 7, 2020 [Zoom](https://zoom.us/rec/share/DWTjWuRAuLwnBlvdRBCCkA9l0Cnq18pBTZizcetxmNsOLO5v66iOyN28hdJf9kxE.Pw5tYmcSSN8zafVJ?startTime=1588866827000) [Youtube](https://www.youtube.com/watch?v=xtdcaOzoacU)
* Jun 11, 2020 [Zoom](https://zoom.us/rec/share/ZALZXapVR3jXbuI_CpuSDg28HcBGStU6dGbOCUTHYaEysS_5Vp5vfW4fey3XUfdX.RcDi8F_dvSjeHR-3?startTime=1591891006000) [Youtube](https://www.youtube.com/watch?v=936z41Mo1tQ)
* Jul 2, 2020 [Zoom](https://zoom.us/rec/share/OZ32eQiXJFD1UtP3FtWbS-h7W56pagml90U3otr2wYK6rd_XviYYGrVeE6UtOPn-.5Us9KCsW2PTlGzG4?startTime=1593705426000) [Youtube](https://www.youtube.com/watch?v=1eGY7Rti-l8)
* Aug 6, 2020 [Zoom](https://zoom.us/rec/share/vOtMIQZxh21_a7xUzYimaafj5W3Tg8JqXihaHhcSZN-MnnkfFWmBrtH9P1ai2L9o.UDogVkEsxYACCUca?startTime=1596729252000) [Youtube](https://www.youtube.com/watch?v=FYF15RA9H3k)
* Sep 3, 2020 [Zoom](https://zoom.us/rec/share/G-VDxzY0v3epqLIeG_TbNy5jwxGgOR1kwzayMMpB5hpnlSJ1v9gbZR5x_REmN3jg.82jdi-Oz85J-REou?startTime=1599148704000) [Youtube](https://www.youtube.com/watch?v=Y4FuML4ju-s)
* Oct 1, 2020 [Zoom](https://zoom.us/rec/share/5Z3dUPoHS_LC0jIvjIzj2o-wZ9-UVYHzrYFJBaxMOgcvlqVDw-ZlgoNDCM4Mh0R0.u1_avgEdWwoY2Vje?startTime=1601567892000) [Youtube](https://www.youtube.com/watch?v=xFPLIv9X1vU) **Password**: `graphqlwg_2020`
* Nov 5, 2020 [Zoom](https://zoom.us/rec/share/I11umlo7WcCz0eO5T60Ej--5xwTW609hwXAZ9ACDR_7GfNB2Pbb6GD5DRTou6bec.mKWNDVhXS529e7wM) [Youtube](https://www.youtube.com/watch?v=UybZp9O24Ow) **Password**: `graphqlwg_2020`
* Dec 3, 2020 [Zoom](https://zoom.us/rec/share/p2FPa_zWvdYlTiH8d9fy5BPNdlhm1_a_Db1Iy1Ktnc1EootCfrPOgXwrqiZqCMsW.chft7R9pbEk8zown) Youtube?? **Password**: `graphqlwg_2020`

## Input union subgroup

* Apr 30, 2020 [Zoom](https://zoom.us/rec/share/MEafglhve2bjypDnJ0hqoGEC0oViebxlQXhc4O5I236LVEQTAmzzQwxrNJ0UqLDD.hKJ7MbVM8S_xxnKw?startTime=1588262056000) **Youtube?**
* May 28, 2020 [Zoom](https://zoom.us/rec/share/qSV-MXOgNa_bDE0mgY-geHArjr-JEtKaePW5hvfKo_U-D58ARtZn667TLvEB4CDE.hKEcKcoNoeW4Vv4l?startTime=1590681409000) [Youtube](https://www.youtube.com/watch?v=4NSTbtXRCqY)

**Comment by brianwarner** [comment] 2020-10-15 13:23
Hi,

If that URL is too long to remember, you can also go to https://youtube.graphql.org :-)

Also, the October 1, 2020 and Apr 30, 2020 videos are now uploaded. Thanks for finding those, @IvanGoncharov, I wasn't aware we'd missed the input union video.

Also, yes - to confirm, the Zoom links will expire when the account runs out of storage. On some Zoom accounts they expire after a certain number of days, but I've confirmed we don't currently have that enabled for this particular one.

**Comment by benjie** [comment] 2020-11-08 15:32
I can't seem to get into the Zoom recordings (want access to their transcripts) as either the link or the password for Oct 1 2020 seems to be incorrect?

**Comment by brianwarner** [comment] 2020-11-08 18:27
I'll find you on slack and we can figure it out.

**Comment by IvanGoncharov** [comment] 2020-11-09 15:57
@brianwarner @benjie I updated the message with a password for Oct1.

**Comment by benjie** [comment] 2020-11-09 18:32
Thanks @IvanGoncharov

**Comment by leebyron** [comment] 2021-07-02 17:51
Closing this issue since these are all on the youtube page now

**Closed by leebyron** 2021-07-02 17:51 UTC
